'use server'


import { createClient } from '@/lib/supabase/server'
import { enquirySchema, contactSchema } from '@/lib/validations'
import type { ActionResult, Lead } from '@/types'


// ============================================================
// SUBMIT ENQUIRY
// Public action — creates a lead in Supabase
// Uses service role to bypass RLS but enforces strict server-side validation
// ============================================================
export async function submitEnquiry(
  formData: unknown,
  clientIp = 'unknown'
): Promise<ActionResult<{ lead_number: string }>> {
  try {
    // Rate limiting via Postgres
    const supabase = await createClient()
    const { data: limitOk } = await supabase.rpc('check_rate_limit', { client_ip: clientIp })
    if (!limitOk) {
      return {
        success: false,
        error: 'Too many requests. Please wait a moment before submitting again.',
      }
    }

    // Validate input
    const parsed = enquirySchema.safeParse(formData)
    if (!parsed.success) {
      const fieldErrors: Record<string, string[]> = {}
      for (const issue of parsed.error.issues) {
        const field = issue.path[0] as string
        if (!fieldErrors[field]) fieldErrors[field] = []
        fieldErrors[field].push(issue.message)
      }
      return { success: false, error: 'Validation failed', fieldErrors }
    }

    const data = parsed.data

    // Honeypot check — if filled, silently succeed (don't reveal bot detection)
    if (data.honeypot && data.honeypot.length > 0) {
      return {
        success: true,
        data: { lead_number: 'LEAD-000000' },
      }
    }

    // Use service role client to insert lead server-side
    // (We now reuse the supabase client created for rate limiting)

    // Verify service_id belongs to service_category_id if both provided
    if (data.service_id && data.service_category_id) {
      const { data: service, error: serviceError } = await supabase
        .from('services')
        .select('id, category_id, is_active')
        .eq('id', data.service_id)
        .single()

      if (serviceError || !service || !service.is_active) {
        return { success: false, error: 'Invalid service selected.' }
      }

      if (service.category_id !== data.service_category_id) {
        return { success: false, error: 'Service does not belong to the selected category.' }
      }
    }

    // Insert lead — lead_number is generated by DB default
    const { data: lead, error } = await supabase
      .from('leads')
      .insert({
        customer_name: data.customer_name,
        phone: data.phone,
        email: data.email || null,
        service_category_id: data.service_category_id || null,
        service_id: data.service_id || null,
        location: data.location || null,
        address: data.address || null,
        preferred_date: data.preferred_date || null,
        preferred_time: data.preferred_time || null,
        requirement: data.requirement,
        budget: data.budget || null,
        source: data.source || 'WEBSITE',
        status: 'NEW',
        priority: 'MEDIUM',
        assigned_to: null,
        custom_fields: data.custom_fields || {},
        honeypot: null, // Never store honeypot value
      })
      .select('id, lead_number')
      .single()

    if (error || !lead) {
      console.error('Lead insert error:', error)
      return {
        success: false,
        error: 'We could not process your request. Please try again.',
      }
    }

    // Record activity
    await supabase.from('lead_activities').insert({
      lead_id: lead.id,
      admin_id: null,
      activity_type: 'LEAD_CREATED',
      description: `Enquiry received from ${data.customer_name} via ${data.source || 'WEBSITE'}`,
      metadata: { source: data.source || 'WEBSITE' },
    })

    return {
      success: true,
      data: { lead_number: lead.lead_number },
    }
  } catch (err) {
    console.error('submitEnquiry error:', err)
    return {
      success: false,
      error: 'An unexpected error occurred. Please try again.',
    }
  }
}

// ============================================================
// UPLOAD ATTACHMENT
// Public action — uploads file to Supabase Storage
// ============================================================
export async function uploadLeadAttachment(
  leadId: string,
  leadNumber: string,
  formData: FormData
): Promise<ActionResult<{ file_path: string; file_name: string }>> {
  try {
    const file = formData.get('file') as File
    if (!file) {
      return { success: false, error: 'No file provided.' }
    }

    // Validate file type
    const allowedTypes = [
      'image/jpeg', 'image/png', 'image/gif', 'image/webp',
      'application/pdf', 'application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    ]
    if (!allowedTypes.includes(file.type)) {
      return { success: false, error: 'File type not allowed.' }
    }

    // Validate file size (10MB max)
    if (file.size > 10 * 1024 * 1024) {
      return { success: false, error: 'File size exceeds 10MB limit.' }
    }

    // Sanitize filename
    const sanitizedName = file.name.replace(/[^a-zA-Z0-9._-]/g, '_')
    const filePath = `${leadNumber}/${Date.now()}_${sanitizedName}`

    const supabase = await createClient()

    const { data: uploadData, error: uploadError } = await supabase.storage
      .from('lead-attachments')
      .upload(filePath, file, {
        cacheControl: '3600',
        upsert: false,
      })

    if (uploadError || !uploadData) {
      console.error('Upload error:', uploadError)
      return { success: false, error: 'File upload failed. Please try again.' }
    }

    // Record attachment metadata
    const { error: attachError } = await supabase.from('lead_attachments').insert({
      lead_id: leadId,
      file_name: file.name,
      file_path: uploadData.path,
      file_type: file.type,
      file_size: file.size,
    })

    if (attachError) {
      console.error('Attachment record error:', attachError)
      // Don't fail — file is uploaded, metadata can be added manually
    }

    // Record activity
    await supabase.from('lead_activities').insert({
      lead_id: leadId,
      admin_id: null,
      activity_type: 'FILE_UPLOADED',
      description: `File attached: ${file.name}`,
      metadata: { file_name: file.name, file_size: file.size },
    })

    return {
      success: true,
      data: { file_path: uploadData.path, file_name: file.name },
    }
  } catch (err) {
    console.error('uploadLeadAttachment error:', err)
    return { success: false, error: 'File upload failed.' }
  }
}

// ============================================================
// SUBMIT CONTACT MESSAGE
// Public action
// ============================================================
export async function submitContactMessage(
  formData: unknown
): Promise<ActionResult> {
  try {
    const parsed = contactSchema.safeParse(formData)
    if (!parsed.success) {
      const fieldErrors: Record<string, string[]> = {}
      for (const issue of parsed.error.issues) {
        const field = issue.path[0] as string
        if (!fieldErrors[field]) fieldErrors[field] = []
        fieldErrors[field].push(issue.message)
      }
      return { success: false, error: 'Validation failed', fieldErrors }
    }

    const data = parsed.data
    const supabase = await createClient()

    const { error } = await supabase.from('contact_messages').insert({
      name: data.name,
      email: data.email,
      phone: data.phone || null,
      message: data.message,
    })

    if (error) {
      console.error('Contact message error:', error)
      return { success: false, error: 'Could not send message. Please try again.' }
    }

    return { success: true }
  } catch (err) {
    console.error('submitContactMessage error:', err)
    return { success: false, error: 'An unexpected error occurred.' }
  }
}

// ============================================================
// GET PUBLIC SERVICES (with categories)
// ============================================================
export async function getPublicServices() {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from('services')
    .select(`
      *,
      service_categories!inner(*)
    `)
    .eq('is_active', true)
    .eq('service_categories.is_active', true)
    .order('sort_order', { ascending: true })

  if (error) {
    console.error('getPublicServices error:', error)
    return []
  }
  return data || []
}

// ============================================================
// GET PUBLIC CATEGORIES
// ============================================================
export async function getPublicCategories() {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from('service_categories')
    .select('*')
    .eq('is_active', true)
    .order('sort_order', { ascending: true })

  if (error) {
    console.error('getPublicCategories error:', error)
    return []
  }
  return data || []
}

// ============================================================
// GET SERVICE BY SLUG
// ============================================================
export async function getServiceBySlug(slug: string) {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from('services')
    .select(`
      *,
      service_categories(*)
    `)
    .eq('slug', slug)
    .eq('is_active', true)
    .single()

  if (error) {
    return null
  }
  return data
}

// ============================================================
// GET SERVICE AREAS
// ============================================================
export async function getPublicServiceAreas() {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from('service_areas')
    .select('*')
    .eq('is_active', true)
    .order('name', { ascending: true })

  if (error) {
    console.error('getPublicServiceAreas error:', error)
    return []
  }
  return data || []
}
